apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob-observer
  namespace: solar-production
  labels:
    reflection.proxy.projectcapsule.dev/enabled: "true"
subjects:
  - kind: User
    name: bob
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
