apiVersion: capsule.clastix.io/v1beta2
kind: TenantResource
metadata:
  name: solar-registry-credentials
  namespace: solar-development
spec:
  serviceAccount:
    name: config-replicator
  resyncPeriod: 10s
  resources:
    - namespaceSelector:
        matchLabels:
          environment: prod
      namespacedItems:
        - apiVersion: v1
          kind: Secret
          namespace: solar-development
          selector:
            matchLabels:
              distribute: solar-registry
