apiVersion: v1
kind: Pod
metadata:
  name: forbidden-priority
  namespace: solar-production
spec:
  priorityClassName: operations-critical
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: hello
      image: busybox:1.37.0
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: 128m
          memory: 256Mi
        limits:
          cpu: 128m
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ALL]
  restartPolicy: Never
