apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../quickstart
patches:
  - path: rules.yaml
    target:
      group: capsule.clastix.io
      version: v1beta2
      kind: Tenant
      name: solar
